=== joelspang/mis_android/prak3/DoodleClient/src/mis/examples/doodle/schemas/poll.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://doodle.com/xsd1" xmlns:tns="http://doodle.com/xsd1"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			Poll schema for RESTful Doodle API.
			$Id$
			Copyright 2007-2008 Inturico Engineering GmbH
			Copyright 2008-2012 Doodle AG
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:include schemaLocation="comment.xsd"/>
	
	<xsd:include schemaLocation="participant.xsd"/>	
	
	<xsd:include schemaLocation="feature.xsd"/>

	<xsd:element name="poll" type="tns:PollType"/>
	
	<xsd:complexType name="PollType">
		<xsd:sequence>
			<xsd:element name="latestChange" type="xsd:dateTime" minOccurs="0"/>
			<xsd:element name="type" type="tns:PollTypeType" minOccurs="0"/>
			<xsd:element name="extensions" type="tns:ExtensionsType" minOccurs="0"/>
			<xsd:element name="hidden" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="writeOnce" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="requireAddress" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="requireEMail" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="requirePhone" type="xsd:boolean" minOccurs="0"/>
			<xsd:element name="byInvitationOnly" type="tns:ByInvitationOnlyType" minOccurs="0"/>
			<xsd:element name="levels" type="tns:LevelsType" minOccurs="0"/>
			<xsd:element name="state" type="tns:StatesType" minOccurs="0"/>
			<xsd:element name="language" type="tns:LanguagesType" minOccurs="0"/>
			<xsd:element name="title" type="xsd:string"/>
			<xsd:element name="location" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string"/>
			<xsd:element name="initiator" type="tns:InitiatorType"/>
			<xsd:element name="options" type="tns:OptionsType"/>
			<xsd:element name="participants" type="tns:ParticipantsType" minOccurs="0"/>
			<xsd:element name="comments" type="tns:CommentsType" minOccurs="0"/>
			<xsd:element name="mandator" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="features" type="tns:FeaturesType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="PollTypeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="DATE"/>
			<xsd:enumeration value="TEXT"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="ExtensionsType">
			<xsd:attribute name="timeZone" type="xsd:boolean"/>
			<xsd:attribute name="columnConstraint" type="tns:ColumnConstraintType"/>
			<xsd:attribute name="rowConstraint" type="tns:RowConstraintType"/>
	</xsd:complexType>
	
	<xsd:complexType name="ByInvitationOnlyType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:boolean">
				<xsd:attribute name="nrOfInvitees" type="xsd:integer"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
	<xsd:simpleType name="ColumnConstraintType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="RowConstraintType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="LevelsType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="2"/>
			<xsd:maxInclusive value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="StatesType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="OPEN"/>
			<xsd:enumeration value="CLOSED"/>
			<xsd:enumeration value="DELETED"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="LanguagesType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="aa"/>
			<xsd:enumeration value="ab"/>
			<xsd:enumeration value="ae"/>
			<xsd:enumeration value="af"/>
			<xsd:enumeration value="ak"/>
			<xsd:enumeration value="am"/>
			<xsd:enumeration value="an"/>
			<xsd:enumeration value="ar"/>
			<xsd:enumeration value="as"/>
			<xsd:enumeration value="av"/>
			<xsd:enumeration value="ay"/>
			<xsd:enumeration value="az"/>
			<xsd:enumeration value="ba"/>
			<xsd:enumeration value="be"/>
			<xsd:enumeration value="bg"/>
			<xsd:enumeration value="bh"/>
			<xsd:enumeration value="bi"/>
			<xsd:enumeration value="bm"/>
			<xsd:enumeration value="bn"/>
			<xsd:enumeration value="bo"/>
			<xsd:enumeration value="br"/>
			<xsd:enumeration value="bs"/>
			<xsd:enumeration value="ca"/>
			<xsd:enumeration value="ce"/>
			<xsd:enumeration value="ch"/>
			<xsd:enumeration value="co"/>
			<xsd:enumeration value="cr"/>
			<xsd:enumeration value="cs"/>
			<xsd:enumeration value="cu"/>
			<xsd:enumeration value="cv"/>
			<xsd:enumeration value="cy"/>
			<xsd:enumeration value="da"/>
			<xsd:enumeration value="de"/>
			<xsd:enumeration value="dv"/>
			<xsd:enumeration value="dz"/>
			<xsd:enumeration value="ee"/>
			<xsd:enumeration value="el"/>
			<xsd:enumeration value="en"/>
			<xsd:enumeration value="eo"/>
			<xsd:enumeration value="es"/>
			<xsd:enumeration value="et"/>
			<xsd:enumeration value="eu"/>
			<xsd:enumeration value="fa"/>
			<xsd:enumeration value="ff"/>
			<xsd:enumeration value="fi"/>
			<xsd:enumeration value="fj"/>
			<xsd:enumeration value="fo"/>
			<xsd:enumeration value="fr"/>
			<xsd:enumeration value="fy"/>
			<xsd:enumeration value="ga"/>
			<xsd:enumeration value="gd"/>
			<xsd:enumeration value="gl"/>
			<xsd:enumeration value="gn"/>
			<xsd:enumeration value="gu"/>
			<xsd:enumeration value="gv"/>
			<xsd:enumeration value="ha"/>
			<xsd:enumeration value="he"/>
			<xsd:enumeration value="hi"/>
			<xsd:enumeration value="ho"/>
			<xsd:enumeration value="hr"/>
			<xsd:enumeration value="ht"/>
			<xsd:enumeration value="hu"/>
			<xsd:enumeration value="hy"/>
			<xsd:enumeration value="hz"/>
			<xsd:enumeration value="ia"/>
			<xsd:enumeration value="id"/>
			<xsd:enumeration value="ie"/>
			<xsd:enumeration value="ig"/>
			<xsd:enumeration value="ii"/>
			<xsd:enumeration value="ik"/>
			<xsd:enumeration value="in"/>
			<xsd:enumeration value="io"/>
			<xsd:enumeration value="is"/>
			<xsd:enumeration value="it"/>
			<xsd:enumeration value="iu"/>
			<xsd:enumeration value="iw"/>
			<xsd:enumeration value="ja"/>
			<xsd:enumeration value="ji"/>
			<xsd:enumeration value="jv"/>
			<xsd:enumeration value="ka"/>
			<xsd:enumeration value="kg"/>
			<xsd:enumeration value="ki"/>
			<xsd:enumeration value="kj"/>
			<xsd:enumeration value="kk"/>
			<xsd:enumeration value="kl"/>
			<xsd:enumeration value="km"/>
			<xsd:enumeration value="kn"/>
			<xsd:enumeration value="ko"/>
			<xsd:enumeration value="kr"/>
			<xsd:enumeration value="ks"/>
			<xsd:enumeration value="ku"/>
			<xsd:enumeration value="kv"/>
			<xsd:enumeration value="kw"/>
			<xsd:enumeration value="ky"/>
			<xsd:enumeration value="la"/>
			<xsd:enumeration value="lb"/>
			<xsd:enumeration value="lg"/>
			<xsd:enumeration value="li"/>
			<xsd:enumeration value="ln"/>
			<xsd:enumeration value="lo"/>
			<xsd:enumeration value="lt"/>
			<xsd:enumeration value="lu"/>
			<xsd:enumeration value="lv"/>
			<xsd:enumeration value="mg"/>
			<xsd:enumeration value="mh"/>
			<xsd:enumeration value="mi"/>
			<xsd:enumeration value="mk"/>
			<xsd:enumeration value="ml"/>
			<xsd:enumeration value="mn"/>
			<xsd:enumeration value="mo"/>
			<xsd:enumeration value="mr"/>
			<xsd:enumeration value="ms"/>
			<xsd:enumeration value="mt"/>
			<xsd:enumeration value="my"/>
			<xsd:enumeration value="na"/>
			<xsd:enumeration value="nb"/>
			<xsd:enumeration value="nd"/>
			<xsd:enumeration value="ne"/>
			<xsd:enumeration value="ng"/>
			<xsd:enumeration value="nl"/>
			<xsd:enumeration value="nn"/>
			<xsd:enumeration value="no"/>
			<xsd:enumeration value="nr"/>
			<xsd:enumeration value="nv"/>
			<xsd:enumeration value="ny"/>
			<xsd:enumeration value="oc"/>
			<xsd:enumeration value="oj"/>
			<xsd:enumeration value="om"/>
			<xsd:enumeration value="or"/>
			<xsd:enumeration value="os"/>
			<xsd:enumeration value="pa"/>
			<xsd:enumeration value="pi"/>
			<xsd:enumeration value="pl"/>
			<xsd:enumeration value="ps"/>
			<xsd:enumeration value="pt"/>
			<xsd:enumeration value="qu"/>
			<xsd:enumeration value="rm"/>
			<xsd:enumeration value="rn"/>
			<xsd:enumeration value="ro"/>
			<xsd:enumeration value="ru"/>
			<xsd:enumeration value="rw"/>
			<xsd:enumeration value="sa"/>
			<xsd:enumeration value="sc"/>
			<xsd:enumeration value="sd"/>
			<xsd:enumeration value="se"/>
			<xsd:enumeration value="sg"/>
			<xsd:enumeration value="si"/>
			<xsd:enumeration value="sk"/>
			<xsd:enumeration value="sl"/>
			<xsd:enumeration value="sm"/>
			<xsd:enumeration value="sn"/>
			<xsd:enumeration value="so"/>
			<xsd:enumeration value="sq"/>
			<xsd:enumeration value="sr"/>
			<xsd:enumeration value="ss"/>
			<xsd:enumeration value="st"/>
			<xsd:enumeration value="su"/>
			<xsd:enumeration value="sv"/>
			<xsd:enumeration value="sw"/>
			<xsd:enumeration value="ta"/>
			<xsd:enumeration value="te"/>
			<xsd:enumeration value="tg"/>
			<xsd:enumeration value="th"/>
			<xsd:enumeration value="ti"/>
			<xsd:enumeration value="tk"/>
			<xsd:enumeration value="tl"/>
			<xsd:enumeration value="tn"/>
			<xsd:enumeration value="to"/>
			<xsd:enumeration value="tr"/>
			<xsd:enumeration value="ts"/>
			<xsd:enumeration value="tt"/>
			<xsd:enumeration value="tw"/>
			<xsd:enumeration value="ty"/>
			<xsd:enumeration value="ug"/>
			<xsd:enumeration value="uk"/>
			<xsd:enumeration value="ur"/>
			<xsd:enumeration value="uz"/>
			<xsd:enumeration value="ve"/>
			<xsd:enumeration value="vi"/>
			<xsd:enumeration value="vo"/>
			<xsd:enumeration value="wa"/>
			<xsd:enumeration value="wo"/>
			<xsd:enumeration value="xh"/>
			<xsd:enumeration value="yi"/>
			<xsd:enumeration value="yo"/>
			<xsd:enumeration value="za"/>
			<xsd:enumeration value="zh"/>
			<xsd:enumeration value="zu"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="InitiatorType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="userId" type="xsd:string" minOccurs="0"/>
			<xsd:element name="eMailAddress" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="OptionsType">
		<xsd:sequence>
			<xsd:element name="option" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="date" type="xsd:date"/>
							<xsd:attribute name="dateTime" type="xsd:dateTime"/>
							<xsd:attribute name="startDateTime" type="xsd:dateTime"/>
							<xsd:attribute name="endDateTime" type="xsd:dateTime"/>
							<xsd:attribute name="final" type="xsd:boolean"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="ParticipantsType">
		<xsd:sequence>
			<xsd:element name="participant" minOccurs="0" maxOccurs="unbounded" type="tns:ParticipantType"/>
		</xsd:sequence>
		<xsd:attribute name="nrOf" type="xsd:integer"/>
	</xsd:complexType>
	
	<xsd:complexType name="CommentsType">
		<xsd:sequence>
			<xsd:element name="comment" minOccurs="0" maxOccurs="unbounded" type="tns:CommentType"/>
		</xsd:sequence>
		<xsd:attribute name="nrOf" type="xsd:integer"/>
	</xsd:complexType>

</xsd:schema>

=== joelspang/mis_android/prak3/DoodleClient/src/mis/examples/doodle/schemas/poll.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:poll xmlns:tns="http://doodle.com/xsd1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://doodle.com/xsd1 poll.xsd ">
  <tns:latestChange>2001-12-31T12:00:00</tns:latestChange>
  <tns:type>DATE</tns:type>
  <tns:extensions columnConstraint="0" rowConstraint="0" timeZone="true"/>
  <tns:hidden>true</tns:hidden>
  <tns:writeOnce>true</tns:writeOnce>
  <tns:requireAddress>true</tns:requireAddress>
  <tns:requireEMail>true</tns:requireEMail>
  <tns:requirePhone>true</tns:requirePhone>
  <tns:byInvitationOnly nrOfInvitees="0">true</tns:byInvitationOnly>
  <tns:levels>0</tns:levels>
  <tns:state>OPEN</tns:state>
  <tns:language>aa</tns:language>
  <tns:title>tns:title</tns:title>
  <tns:location>tns:location</tns:location>
  <tns:description>tns:description</tns:description>
  <tns:initiator>
    <tns:name>tns:name</tns:name>
    <tns:userId>tns:userId</tns:userId>
    <tns:eMailAddress>tns:eMailAddress</tns:eMailAddress>
  </tns:initiator>
  <tns:options>
    <tns:option date="2001-01-01" dateTime="2001-12-31T12:00:00" endDateTime="2001-12-31T12:00:00" final="true" startDateTime="2001-12-31T12:00:00">tns:option</tns:option>
  </tns:options>
  <tns:participants nrOf="0">
    <tns:participant>tns:participant</tns:participant>
  </tns:participants>
  <tns:comments nrOf="0">
    <tns:comment>tns:comment</tns:comment>
  </tns:comments>
  <tns:mandator>0</tns:mandator>
  <tns:features>tns:features</tns:features>
</tns:poll>
